Sender: LSF System <lsfadmin@lo-dgx1-003>
Subject: Job 2282331: <python classifier1.py --is_cluster=True --test_on_query=True --restore_ckpt=True --ckpt_path=/cluster/home/woonmi/CIL_project/Classifier/checkpoints/res1000/fft_resnet/cp-0109.ckpt.data-00000-of-00001> in cluster <leonhard> Exited

Job <python classifier1.py --is_cluster=True --test_on_query=True --restore_ckpt=True --ckpt_path=/cluster/home/woonmi/CIL_project/Classifier/checkpoints/res1000/fft_resnet/cp-0109.ckpt.data-00000-of-00001> was submitted from host <lo-login-02> by user <woonmi> in cluster <leonhard> at Mon Jun 24 15:03:07 2019
Job was executed on host(s) <20*lo-dgx1-003>, in queue <gpu.24h>, as user <woonmi> in cluster <leonhard> at Mon Jun 24 15:04:40 2019
</cluster/home/woonmi> was used as the home directory.
</cluster/home/woonmi/CIL_project/Classifier> was used as the working directory.
Started at Mon Jun 24 15:04:40 2019
Terminated at Mon Jun 24 15:04:48 2019
Results reported at Mon Jun 24 15:04:48 2019

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
python classifier1.py --is_cluster=True --test_on_query=True --restore_ckpt=True --ckpt_path=/cluster/home/woonmi/CIL_project/Classifier/checkpoints/res1000/fft_resnet/cp-0109.ckpt.data-00000-of-00001
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   4.70 sec.
    Max Memory :                                 145 MB
    Average Memory :                             78.00 MB
    Total Requested Memory :                     100000.00 MB
    Delta Memory :                               99855.00 MB
    Max Swap :                                   -
    Max Processes :                              3
    Max Threads :                                4
    Run time :                                   8 sec.
    Turnaround time :                            101 sec.

The output (if any) follows:

/cluster/apps/python/3.6.4/lib64/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2.0.0-alpha0
Searching for images in /cluster/home/woonmi/dataset/cil-cosmology-2018/cosmology_aux_data_170429/query
Found Labels
Traceback (most recent call last):
  File "classifier1.py", line 467, in <module>
    model = tf.keras.models.model_from_json(json_config, custom_objects=custom_objects)
  File "/cluster/home/woonmi/.local/lib64/python3.6/site-packages/tensorflow/python/keras/saving/model_config.py", line 96, in model_from_json
    return deserialize(config, custom_objects=custom_objects)
  File "/cluster/home/woonmi/.local/lib64/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 95, in deserialize
    printable_module_name='layer')
  File "/cluster/home/woonmi/.local/lib64/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 192, in deserialize_keras_object
    list(custom_objects.items())))
  File "/cluster/home/woonmi/.local/lib64/python3.6/site-packages/tensorflow/python/keras/engine/sequential.py", line 351, in from_config
    custom_objects=custom_objects)
  File "/cluster/home/woonmi/.local/lib64/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 95, in deserialize
    printable_module_name='layer')
  File "/cluster/home/woonmi/.local/lib64/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 181, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "/cluster/home/woonmi/.local/lib64/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 166, in class_and_config_for_serialized_keras_object
    raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown layer: ResBlock
